"""Evidence-bundle writer.

One Recorder per variant. Writes terminal.jsonl, events.jsonl,
summary.md, and result.tap into <out>/<variant>/. The terminal log is
the project-local v1 format described in
docs/simulation-design-plan.md §Evidence Bundle — it is NOT asciicast
v3 and does not use a .cast extension.

terminal.jsonl rows:
    {"ts": float, "dir": "in"|"out", "enc": "utf8"|"b64",
     "data": str, "len": int}

events.jsonl rows:
    {"ts": float, "kind": str, "intent": str, "screen_id": str,
     "payload": object}

A pair-of-runs diff is the dispatcher's job; this module only writes
single-variant artifacts.
"""

from __future__ import annotations

import base64
import datetime
import json
import os
from typing import Any, Dict, Iterable, List, Optional


HARNESS_VERSION = "0.1.0"


def _safe_text(data: bytes) -> Dict[str, Any]:
    """Encode arbitrary bytes for terminal.jsonl.

    Plain UTF-8 is recorded verbatim. Anything that does not round-trip
    UTF-8 cleanly is base64-encoded; reviewers can still reconstruct
    the byte stream without a separate raw recording. Each row carries
    the original byte length so a downstream consumer can verify it.
    """
    try:
        as_text = data.decode("utf-8")
    except UnicodeDecodeError:
        return {
            "enc": "b64",
            "data": base64.b64encode(data).decode("ascii"),
            "len": len(data),
        }
    return {"enc": "utf8", "data": as_text, "len": len(data)}


class Recorder:
    """Per-variant evidence writer.

    The Recorder is append-only and synchronous: each terminal chunk
    or event is fsynced-by-implication via the OS write buffer. v1
    does not promise crash-consistency.
    """

    def __init__(self, out_dir: str):
        os.makedirs(out_dir, exist_ok=True)
        self.out_dir = out_dir
        self._terminal_path = os.path.join(out_dir, "terminal.jsonl")
        self._events_path = os.path.join(out_dir, "events.jsonl")
        self._terminal_fp = open(self._terminal_path, "w", encoding="utf-8")
        self._events_fp = open(self._events_path, "w", encoding="utf-8")
        self._closed = False

    def write_terminal(self, ts: float, direction: str, data: bytes) -> None:
        if self._closed:
            return
        row = {"ts": round(ts, 6), "dir": direction}
        row.update(_safe_text(data))
        self._terminal_fp.write(json.dumps(row, ensure_ascii=False) + "\n")
        self._terminal_fp.flush()

    def write_event(
        self,
        ts: float,
        kind: str,
        intent: str = "",
        screen_id: str = "",
        payload: Optional[Dict[str, Any]] = None,
    ) -> None:
        if self._closed:
            return
        row = {
            "ts": round(ts, 6),
            "kind": kind,
            "intent": intent,
            "screen_id": screen_id,
            "payload": payload or {},
        }
        self._events_fp.write(json.dumps(row, ensure_ascii=False) + "\n")
        self._events_fp.flush()

    def write_summary(
        self,
        host_inputs: Dict[str, Any],
        run_meta: Dict[str, Any],
        outcome: Dict[str, Any],
        known_rough_edges: Iterable[Dict[str, str]],
    ) -> None:
        path = os.path.join(self.out_dir, "summary.md")
        with open(path, "w", encoding="utf-8") as fp:
            fp.write("---\n")
            fp.write("title: Stage 1 simulation summary\n")
            fp.write("category: audit\n")
            fp.write("component: stage1-sim\n")
            fp.write("status: evidence\n")
            fp.write(
                "version: %s\n" % HARNESS_VERSION,
            )
            fp.write(
                "last_updated: %s\n"
                % datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d"),
            )
            fp.write("tags: [audit, simulation, stage1, pty]\n")
            fp.write("priority: medium\n")
            fp.write("---\n\n")

            fp.write(
                "# Stage 1 baseline — variant `%s`\n\n" % run_meta.get("variant", "")
            )
            fp.write(
                "Generated by `scripts/sim/run.py` (harness v%s) as Slice 1 of\n"
                "`docs/simulation-design-plan.md`.\n\n" % HARNESS_VERSION
            )

            fp.write("## Run metadata\n\n")
            for key in (
                "run_id",
                "persona",
                "stage",
                "variant",
                "started_at_utc",
                "duration_seconds",
                "harness_version",
                "shelltutor_path",
                "shelltutor_path_used",
                "sandbox_root",
                "pty_geometry",
                "per_sentinel_timeout_seconds",
            ):
                if key in run_meta:
                    fp.write("- %s: `%s`\n" % (key, run_meta[key]))
            fp.write("\n")

            fp.write("## Host inputs\n\n")
            fp.write(
                "Slice 1 isolates only the `/etc/bashrc` source statement (in the\n"
                "`no-system-rc-preview` variant). All other host inputs still bleed\n"
                "into the captured transcript — they are recorded here so later\n"
                "reviewers do not over-read the current-vs-preview diff.\n\n"
            )
            for key in (
                "term",
                "columns",
                "lines",
                "path_sha256_prefix",
                "python_version",
                "uname_system",
                "uname_release",
                "platform_machine",
            ):
                if key in host_inputs:
                    val = host_inputs[key]
                    val_str = "unset" if val is None else str(val)
                    fp.write("- %s: `%s`\n" % (key, val_str))
            fp.write("\n")

            fp.write("## Outcome\n\n")
            gate_passed = outcome.get("gate_passed", False)
            child_exit = outcome.get("child_exit_code")
            c002 = outcome.get("c002_meaning", "")
            fp.write("- gate_passed: `%s`\n" % str(gate_passed).lower())
            fp.write("- child_exit_code: `%s`\n" % child_exit)
            if c002:
                fp.write("- c002_meaning: `%s`\n" % c002)
            if "harness_exit_code" in outcome:
                fp.write("- harness_exit_code: `%s`\n" % outcome["harness_exit_code"])
            if "notes" in outcome and outcome["notes"]:
                fp.write("\n%s\n" % outcome["notes"])
            fp.write("\n")

            fp.write("## Known rough edges labeled\n\n")
            fp.write(
                "Sourced from `audit/2026-05-23/stage1-density.md` — the audit\n"
                "ordering rule requires these be labeled (not pre-fixed) on the\n"
                "current-rc baseline. The IDs below are embedded in the per-event\n"
                "annotations in `events.jsonl`.\n\n"
            )
            for row in known_rough_edges:
                fp.write(
                    "- **%s** (%s): %s\n"
                    % (
                        row.get("id", "?"),
                        row.get("recommendation", "?"),
                        row.get("note", ""),
                    )
                )
            fp.write("\n")

            fp.write("## File index\n\n")
            fp.write(
                "- `terminal.jsonl` — chunk-level PTY stream (v1 project-local format).\n"
            )
            fp.write(
                "- `events.jsonl` — sentinel matches, persona inputs, gate result.\n"
            )
            fp.write("- `result.tap` — TAP 13 single-test outcome line.\n")

    def write_tap(self, ok: bool, description: str) -> None:
        path = os.path.join(self.out_dir, "result.tap")
        with open(path, "w", encoding="utf-8") as fp:
            fp.write("TAP version 13\n")
            fp.write("1..1\n")
            fp.write(
                "%s 1 - %s\n" % ("ok" if ok else "not ok", description),
            )

    def close(self) -> None:
        if not self._closed:
            self._closed = True
            try:
                self._terminal_fp.close()
            finally:
                self._events_fp.close()


def stage1_known_rough_edges() -> List[Dict[str, str]]:
    """Per docs/simulation-design-plan.md §Evidence Bundle — labeled
    rough edges sourced from the SPLIT / SPLIT-or-TRIM rows of the
    Stage 1 density audit.
    """
    return [
        {
            "id": "S1-L1",
            "recommendation": "SPLIT",
            "note": (
                "1.1 running-commands packs 6 concepts and 5+ distinct actions "
                "(echo + quoting; Tab/Tab-Tab; Ctrl+L; Up; Ctrl+C). Density-audit "
                "calls for a 1.1a/1.1b split. Baseline captures the unsplit screen."
            ),
        },
        {
            "id": "S1-L2",
            "recommendation": "SPLIT or TRIM",
            "note": (
                "1.2 identity/location/time packs 5 concepts and 4 distinct actions "
                "(whoami/pwd/date + clear). Density-audit calls for TRIM (drop clear, "
                "soften the Stage-2 forward-reference) as the conservative fix."
            ),
        },
        {
            "id": "S1-O",
            "recommendation": "keep with watch",
            "note": (
                "Orientation hits the 5-concept ceiling but is intrinsically a "
                "one-screen reference card. Watch baseline evidence before deciding "
                "to split."
            ),
        },
        {
            "id": "S1-L3",
            "recommendation": "keep with watch",
            "note": (
                "1.3 concept density is high but action density is zero (read only). "
                "Risk: information overload after 1.1 and 1.2. Watch for long PTY "
                "pauses before deciding to split."
            ),
        },
    ]
